name: CPP Game Engine preparation

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build_debug_for_windows:
    name: Build debug binary for Windows
    runs-on: windows-latest

    steps:
      - name: Preparing git branch
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.30.1

      - name: Build binary
        run: ./build_windows_debug.bat

  build_for_browser:
    name: Build binary for Browser
    runs-on: windows-latest

    steps:
      - name: Preparing git branch
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.30.1

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build binary
        run: ./build_browser.ps1

      - name: Extend Assembly
        run: ./extend_web_assembly.ps1

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-sandbox
          path: ./build/bin/

  deploy_artifact_for_browser:
    name: Deploy Artifact for Browser
    runs-on: ubuntu-latest
    needs: build_for_browser
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-sandbox
          path: ./deploy/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python server
        run: python deploy/server.py
      
      - name: Start Serveo tunnel
        run: |
          echo "Serveo tunnel starting..."
          nohup ssh -R 80:localhost:8000 serveo.net > serveo.log 2>&1 &
          sleep 30
          cat serveo.log  # Добавим вывод логов для диагностики
          grep -o 'https://[a-z0-9]*\.serveo\.net' serveo.log > serveo_url.txt

      - name: Display Serveo URL
        run: cat serveo_url.txt

      - name: Keep Job Alive
        run: |
          echo "Keeping job alive. Access your server at the URL above."
          tail -f /dev/null